#include "PCH.h"

#include "fx/ParticleModule.h"

namespace cs
{
	DEFINE_META_VECTOR_NEW(ParticleModuleList, ParticleModule, ParticleModuleList);

	BEGIN_META_CLASS(ParticleModuleValue)

	END_META();

	BEGIN_META_MODULE_VALUE_CONSTANT(ParticleModuleValueSize, ADD_PARTICLE_VEC2_OPTIONS);
	BEGIN_META_MODULE_VALUE_LERP(ParticleModuleValueSizeLerp, ADD_PARTICLE_VEC2_OPTIONS);

	BEGIN_META_MODULE_VALUE_CONSTANT(ParticleModuleValueColor, ADD_PARTICLE_COLOR_OPTIONS);
	BEGIN_META_MODULE_VALUE_LERP(ParticleModuleValueColorLerp, ADD_PARTICLE_COLOR_OPTIONS);

	BEGIN_META_MODULE_VALUE_CONSTANT(ParticleModuleValueVelocity, ADD_PARTICLE_VEC3_OPTIONS);
	BEGIN_META_MODULE_VALUE_CONSTANT(ParticleModuleValueAcceleration, ADD_PARTICLE_VEC3_OPTIONS);

	BEGIN_META_MODULE_VALUE_CONSTANT(ParticleModuleValueRotation, ADD_PARTICLE_FLOAT_OPTIONS);
	BEGIN_META_MODULE_VALUE_CONSTANT(ParticleModuleValueRotationSpeed, ADD_PARTICLE_FLOAT_OPTIONS);

	BEGIN_META_CLASS(ParticleModule)

	END_META();

	BEGIN_META_CLASS(ParticleModuleSize)
		ADD_MEMBER_PTR(size);
			ADD_PARTICLE_MODULE_VALUE_SIZE();
	END_META();

	BEGIN_META_CLASS(ParticleModuleColor)
		ADD_MEMBER_PTR(color);
			ADD_PARTICLE_MODULE_VALUE_COLOR();
	END_META();

	BEGIN_META_CLASS(ParticleModuleSimulation)
		ADD_MEMBER_PTR(velocity);
			ADD_PARTICLE_MODULE_VALUE_VELOCITY();
		
		ADD_MEMBER_PTR(acceleration);
			ADD_PARTICLE_MODULE_VALUE_ACCELERATION();

	END_META();

	BEGIN_META_CLASS(ParticleModuleRotation)
		ADD_MEMBER_PTR(start);
			ADD_PARTICLE_MODULE_VALUE_ROTATION();
		ADD_MEMBER_PTR(speed);
			ADD_PARTICLE_MODULE_VALUE_ROTATIONSPEED();
	END_META();

}
